// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ScentSnap",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "ScentSnap",
            targets: ["AppModule"],
            bundleIdentifier: "com.example.apple-samplecode.ScentSnap",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/SwiftUIX/SwiftUIX", "0.1.4"..<"1.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "SwiftUIX", package: "swiftuix")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)